const ASSET='https://maira-beauty-atelier.vercel.app';
const A={
 hero:ASSET+'/assets/hero-C9J-03Tv.jpg',artist:ASSET+'/assets/artist-CMjrWSLo.jpg',space:ASSET+'/assets/space-q4V5CjOp.jpg',video:ASSET+'/media/espaco-levie-manicure.mp4',
 hands:ASSET+'/assets/portal-maos-BdMunZVi.jpg',h1:ASSET+'/assets/maos-1-BPlefsa7.jpg',h2:ASSET+'/assets/maos-2-Bg4ddySz.jpg',h3:ASSET+'/assets/maos-3-CTRtgBhC.jpg',h4:ASSET+'/assets/maos-4-rfh21_iL.jpg',
 feet:ASSET+'/assets/pes-1-Bug6h5o2.jpg',f2:ASSET+'/assets/pes-2-BWfWjU7E.jpg',f3:ASSET+'/assets/pes-3-C8znuF3B.jpg',
 brows:ASSET+'/assets/portal-sobrancelhas-BuZcoaty.jpg',b1:ASSET+'/assets/sobrancelhas-1-Beq9oMk4.jpg',b2:ASSET+'/assets/sobrancelhas-2-SxVcyiSm.jpg',b3:ASSET+'/assets/sobrancelhas-3-D6BRe2ZH.jpg',b4:ASSET+'/assets/sobrancelhas-4-BNWTVAgv.jpg',lacquer:ASSET+'/assets/lacquer-DEZgZfRO.jpg'
};
const WA='https://wa.me/';
const app=document.querySelector('#app');
const home=()=>`<section class="hero grain" data-scene="0"><div class="hero-pin"><div class="ambient"><i></i><i></i><i></i></div><div class="hero-media"><img class="hero-poster" src="${A.hero}" alt="Composição editorial de beleza"><video class="hero-video" src="${A.video}" poster="${A.hero}" muted playsinline autoplay loop></video></div><div class="hero-shade"></div><div class="lacquer-orb"></div><div class="shell hero-copy"><div class="hero-copy-inner"><div class="eyebrow">Maíra Beauty Atelier • mãos • pés • sobrancelhas</div><h1 class="display"><span class="hero-line"><span>BELEZA</span></span><span class="hero-line"><span>DESENHADA EM</span></span><span class="hero-line"><span>CADA DETALHE.</span></span></h1><p class="hero-sub">Um atelier para cuidar dos detalhes que traduzem a sua presença. Descubra os serviços, conheça os trabalhos e escolha o seu próximo ritual.</p><div class="hero-actions"><a class="btn primary" href="/agendar">Agendar meu horário</a><a class="btn" href="/portfolio">Ver portfólio</a></div></div></div><div class="cinema-cut" aria-hidden="true"></div><div class="scroll-mark">Deslize para descobrir ↓</div></div></section>
<section class="manifest grain" data-scene="1"><div class="microtag">ATELIER</div><div class="shell manifest-grid"><div><div class="eyebrow" style="color:var(--ox)">Manifesto</div><h2 class="display">NÃO É SÓ ESTÉTICA.<br>É PRESENÇA.</h2><p>Cada detalhe comunica. A proposta não é criar um personagem, mas revelar forma, proporção e acabamento de um jeito que ainda parece seu.</p><a class="btn" style="color:var(--ink);border-color:rgba(120,30,58,.24)" href="/sobre">Conhecer a filosofia</a></div><div class="portrait-stack"><figure class="portrait-a"><img src="${A.artist}" alt="Retrato editorial da profissional"></figure><figure class="portrait-b"><img src="${A.b3}" alt="Olhar e sobrancelhas em enquadramento editorial"></figure></div></div></section>
<section class="universes" data-scene="2"><div class="universes-pin"><div class="u-head"><div><div class="eyebrow" style="color:var(--ox)">Três matérias</div><h2 class="display">LACA. PÉROLA.<br>PRECISÃO.</h2></div><p>Três universos. Uma assinatura. Cada capítulo muda de matéria sem quebrar a mesma experiência.</p></div><div class="panel-wrap"><article class="universe-card u1"><video src="${A.video}" muted playsinline autoplay loop></video><div class="u-overlay"></div><div class="u-copy"><span class="num">01 • LACA</span><h3>MÃOS & GEL</h3><p>Forma, cor e acabamento ganham profundidade. O brilho deixa de ser detalhe e vira matéria.</p><a class="btn" href="/maos-e-gel">Entrar no capítulo</a></div></article><article class="universe-card u2"><img src="${A.feet}" alt="Cuidado para os pés"><div class="u-overlay"></div><div class="u-copy"><span class="num">02 • PÉROLA</span><h3>PÉS</h3><p>Luz, água e leveza. O movimento desacelera e abre espaço para o cuidado.</p><a class="btn" href="/pes">Entrar no capítulo</a></div></article><article class="universe-card u3"><img src="${A.brows}" alt="Design de sobrancelhas"><div class="u-overlay"></div><div class="u-copy"><span class="num">03 • PRECISÃO</span><h3>SOBRANCELHAS</h3><p>Linha, proporção e expressão. A matéria se afina até virar desenho.</p><a class="btn" href="/sobrancelhas">Entrar no capítulo</a></div></article></div></div></section>
<section class="cinema-interlude grain" data-scene="3"><div class="cinema-pin"><video class="cinema-video" src="${A.video}" poster="${A.hands}" muted playsinline autoplay loop></video><div class="cinema-shade"></div><div class="cinema-beats shell"><div class="cinema-kicker eyebrow">A experiência continua</div><div class="cinema-beat beat-1 display">A MATÉRIA MUDA.</div><div class="cinema-beat beat-2 display">A ASSINATURA NÃO.</div><p class="cinema-note">O movimento da câmera, a luz e o scroll passam a dirigir a página como uma única cena.</p></div></div></section>
<section class="chapter dark grain" data-scene="3"><div class="lacquer-sheet"></div><div class="chapter-inner"><div class="copy"><div class="eyebrow chapter-label">Mãos & Gel • laca em movimento</div><h2 class="display">COR QUE<br>GANHA<br>PRESENÇA.</h2><p>Do desenho da forma ao brilho final: estrutura leve, pigmento profundo e acabamento que pede um segundo olhar.</p><a class="btn primary" href="/maos-e-gel">Explorar Mãos & Gel</a></div><div class="chapter-media hands-media"><div class="frame main"><video src="${A.video}" muted autoplay loop playsinline></video></div><div class="frame small"><img src="${A.h4}" alt="Nail design em detalhe"></div><div class="frame tiny"><img src="${A.lacquer}" alt="Textura borgonha"></div></div></div></section>
<section class="chapter light grain" data-scene="4"><div class="water"></div><div class="chapter-inner"><div class="copy"><div class="eyebrow" style="color:var(--ox)">Pés • pérola e leveza</div><h2 class="display">O RITMO<br>MUDA.</h2><p>Um momento de cuidado que desacelera a narrativa. Superfícies claras, reflexos de água e acabamento limpo fazem a experiência respirar.</p><a class="btn" style="color:var(--ink)" href="/pes">Explorar cuidados para os pés</a></div><div class="chapter-media feet-media"><div class="frame main"><img src="${A.feet}" alt="Pedicure editorial"></div><div class="frame small"><img src="${A.f2}" alt="Acabamento das unhas dos pés"></div><div class="frame tiny"><img src="${A.f3}" alt="Materiais de cuidado"></div></div></div></section>
<section class="chapter dark grain" data-scene="5"><div class="chapter-inner"><div class="copy"><div class="eyebrow chapter-label">Sobrancelhas • precisão</div><h2 class="display">O TRAÇO<br>MUDA TODO<br>O OLHAR.</h2><p>A linha que atravessou a experiência vira mapeamento: início, arco e final. Naturalidade primeiro; precisão em cada decisão.</p><a class="btn primary" href="/sobrancelhas">Descobrir o design</a></div><div class="chapter-media brow-media"><div class="frame main"><img src="${A.b2}" alt="Sobrancelha em macro"></div><div class="frame small"><img src="${A.b4}" alt="Finalização do design"></div><div class="frame tiny"><img src="${A.b1}" alt="Mapeamento da sobrancelha"></div><svg class="precision-svg" viewBox="0 0 700 700"><path pathLength="1" d="M80 470 C 180 310, 320 250, 610 335"/><path pathLength="1" d="M120 520 C 260 390, 430 370, 640 430"/></svg></div></div></section>
<section class="portfolio" data-scene="5"><div class="portfolio-pin"><div class="portfolio-head"><div class="eyebrow" style="color:var(--champ)">Portfólio selecionado</div><h2 class="display">DETALHES QUE<br>CONTAM HISTÓRIAS.</h2></div><div class="track">${[[A.h1,'Mãos & Gel','Borgonha espelhado'],[A.b1,'Sobrancelhas','Mapeamento do arco'],[A.f2,'Pés','Precisão no contorno'],[A.h3,'Mãos & Gel','Nude champagne'],[A.b3,'Sobrancelhas','Expressão equilibrada'],[A.f3,'Pés','O gesto do cuidado']].map(x=>`<figure class="work"><img src="${x[0]}" alt="${x[2]}"><figcaption class="work-cap"><span class="eyebrow">${x[1]}</span><h3>${x[2]}</h3></figcaption></figure>`).join('')}</div></div></section>
<section class="artist grain" data-scene="5"><div class="shell artist-grid"><div class="artist-photo"><img src="${A.artist}" alt="Retrato editorial da profissional"><div class="signature">Maíra</div></div><div><div class="eyebrow" style="color:var(--ox)">A artista por trás dos detalhes</div><h2 class="display">TÉCNICA,<br>INTENÇÃO<br>E ARTE.</h2><p>Cada atendimento começa com observação e escuta. Referências, rotina e estilo pessoal orientam a experiência — do primeiro traço ao acabamento.</p><a class="btn" style="color:var(--ink)" href="/sobre">Conhecer a profissional</a></div></div></section>
<section class="proof grain"><div class="shell"><small>Nossa essência</small><div class="quote">O DETALHE NÃO É O FINAL.<br>É TODO O CAMINHO.</div><p class="note">Em breve, histórias e relatos autorizados de quem viveu a experiência no atelier.</p></div></section>
<section class="ritual" data-scene="5"><div class="shell ritual-grid"><div><div class="eyebrow" style="color:var(--ox)">Monte seu ritual</div><h2 class="display">VOCÊ PASSOU<br>PELOS TRÊS<br>UNIVERSOS.</h2><p>Agora transforme a experiência em escolha. Combine os capítulos que fazem sentido e leve tudo pronto para a conversa no WhatsApp.</p></div><div class="ritual-card"><div class="choice-grid"><button class="choice" data-choice="Mãos & Gel"><i class="dot"></i><div><b>Mãos & Gel</b><span>Forma, cor, gel e nail design.</span></div></button><button class="choice" data-choice="Pés"><i class="dot"></i><div><b>Pés</b><span>Cuidado, esmaltação e acabamento.</span></div></button><button class="choice" data-choice="Sobrancelhas"><i class="dot"></i><div><b>Sobrancelhas</b><span>Mapeamento, desenho e finalização.</span></div></button></div><div class="summary">Seu ritual: <strong id="ritualText">nenhum universo selecionado ainda.</strong></div><a id="ritualWa" class="btn primary" style="margin-top:18px;width:100%" href="/agendar">Planejar meu atendimento</a></div></div></section>
<section class="final grain"><div class="final-bg"></div><div class="shell final-inner"><div class="eyebrow" style="color:var(--champ)">Seu momento</div><h2 class="display">SEU PRÓXIMO DETALHE INESQUECÍVEL COMEÇA AQUI.</h2><a class="btn primary" href="/agendar">Planejar meu atendimento</a></div></section>${footer()}`;
function footer(){return `<footer class="footer"><div class="shell footer-grid"><div><a class="brand" href="/"><strong>MAÍRA</strong><span>Beauty Atelier</span></a><p style="max-width:340px;margin-top:22px">Mãos, pés e sobrancelhas em uma experiência de cuidado criada para realçar o que há de mais único em você.</p></div><div><h4>Navegação</h4><p><a href="/experiencias">Experiências</a><br><a href="/portfolio">Portfólio</a><br><a href="/sobre">Sobre</a><br><a href="/agendar">Agendar</a></p></div><div><h4>Contato</h4><p>Atendimento mediante consulta.<br>Confira os serviços e planeje sua visita.<br><span class="preview-note">Contato oficial a configurar antes da publicação.</span></p></div></div><div class="shell legal">© 2026 Maíra Beauty Atelier • Direção digital cinematográfica CVD</div></footer>`}
const routes={
 '/experiencias':{ey:'Experiências',title:'TRÊS UNIVERSOS. UMA SÓ EXPERIÊNCIA.',support:'Mãos, pés e sobrancelhas não aparecem como serviços soltos. Cada cuidado tem sua própria sensação e intenção — e todos carregam a mesma atenção aos detalhes.',img:A.hero,head:'LACA. PÉROLA. PRECISÃO.',text:'O mesmo código visual muda de matéria conforme o serviço. Isso torna cada experiência reconhecível sem quebrar a unidade da marca.',services:[['Mãos & Gel','Forma, cor e acabamento que expressam seu estilo.'],['Pés','Cuidado, leveza e beleza em cada passo.'],['Sobrancelhas','Harmonia e precisão para transformar o olhar.'],['Método','Consulta, criação, cuidado e finalização.']],gallery:[A.hands,A.feet,A.brows,A.lacquer]},
 '/maos-e-gel':{ey:'Mãos & Gel • forma, cor e brilho',title:'UNHAS QUE VESTEM A SUA PRESENÇA.',support:'Do desenho da forma ao brilho final: estrutura leve, cor precisa e acabamento que permanece impecável no dia a dia.',img:A.hands,head:'FORMA, COR E ACABAMENTO.',text:'Escolha um serviço específico ou comece por uma conversa. Cada opção abre o WhatsApp já com contexto.',services:[['Alongamento em Gel','Estrutura personalizada, leve e elegante.'],['Banho de Gel','Resistência com aparência natural.'],['Esmaltação em Gel','Cor e brilho com acabamento uniforme.'],['Nail Design','Composição de formato, cor e detalhes.']],gallery:[A.h1,A.h2,A.h3,A.h4]},
 '/pes':{ey:'Pés • cuidado e leveza',title:'CUIDADO QUE COMEÇA PELA BASE.',support:'Um ritual de cuidado para trazer leveza, acabamento e bem-estar a cada passo.',img:A.feet,head:'LEVEZA, ACABAMENTO E CUIDADO.',text:'O capítulo mais claro da experiência: ritmo mais calmo, superfícies peroladas e atenção ao detalhe.',services:[['Unhas dos Pés / Pedicure','Cuidado e acabamento personalizado.'],['Esmaltação dos Pés','Cor, precisão e finalização.'],['Cuidados para os Pés','Rotina de cuidado combinada durante o atendimento.'],['Orientação','Cuidados simples para prolongar o resultado.']],gallery:[A.feet,A.f2,A.f3,A.hero]},
 '/sobrancelhas':{ey:'Sobrancelhas • desenho e expressão',title:'O TRAÇO QUE MUDA TODO O OLHAR.',support:'Um desenho personalizado que respeita sua naturalidade, equilibra proporções e revela sua expressão.',img:A.brows,head:'LEITURA. MAPEAMENTO. DESENHO. FINALIZAÇÃO.',text:'A linha deixa de ser decoração e vira linguagem: início, arco, final e expressão conectados em uma única decisão visual.',services:[['Leitura do rosto','Observamos proporção, expressão e crescimento natural.'],['Mapeamento','Pontos de início, arco e final desenhados junto com você.'],['Design','Execução precisa respeitando a densidade natural.'],['Finalização','Ajuste fino e orientações de manutenção.']],gallery:[A.b1,A.b2,A.b3,A.b4]},
 '/portfolio':{ey:'Portfólio',title:'RESULTADOS REAIS. BELEZA AUTORAL.',support:'Uma galeria editorial organizada por universo. A versão final deve usar trabalhos reais autorizados da profissional.',img:A.h1,head:'DETALHES QUE CONTAM HISTÓRIAS.',text:'Aproxime, compare referências e envie o resultado que mais combina com você.',services:[['Mãos & Gel','Forma, cor, estrutura e acabamento.'],['Pés','Cuidado estético e finalização.'],['Sobrancelhas','Naturalidade, proporção e expressão.'],['Referências','Envie uma imagem e alinhe expectativas antes do atendimento.']],gallery:[A.h1,A.b1,A.f2,A.h3,A.b3,A.f3,A.h4,A.b4]},
 '/sobre':{ey:'Sobre a profissional',title:'BELEZA COM INTENÇÃO. DETALHE COM ASSINATURA.',support:'Cada atendimento começa com observação e escuta. Referências, rotina e preferências orientam um trabalho que une técnica, sensibilidade e acabamento.',img:A.artist,head:'A BELEZA MAIS FORTE É A QUE AINDA PARECE SUA.',text:'A proposta do atelier não é criar um personagem. É usar detalhe, proporção, cor e acabamento para revelar presença.',services:[['Escuta antes da técnica','A conversa vem antes do gesto.'],['Personalização real','Forma e desenho definidos para você.'],['Acabamento como assinatura','O detalhe final separa serviço de experiência.'],['Experiência confortável','Ambiente, ritmo e clareza fazem parte do cuidado.']],gallery:[A.artist,A.space,A.h3,A.b3]},
 '/agendar':{ey:'Agendar / contato',title:'MONTE SEU RITUAL. NÓS CUIDAMOS DO RESTO.',support:'Escolha um ou mais universos, selecione o que faz sentido e leve tudo organizado para uma conversa no WhatsApp.',img:A.hero,head:'TRÊS PASSOS. ZERO FRICÇÃO.',text:'Escolha seus serviços, revise a combinação e consulte os horários pelo WhatsApp.',services:[['1. Escolha','Selecione Mãos & Gel, Pés e/ou Sobrancelhas.'],['2. Revise','A combinação aparece organizada antes do envio.'],['3. Consulte','O WhatsApp abre com a mensagem pronta.'],['4. Confirme','A profissional confirma disponibilidade e próximos passos.']],gallery:[A.h1,A.feet,A.b2,A.artist]}
};

function detailGallery(d){return '<section class="institution-gallery"><div class="shell gallery-heading"><div><h2 class="display">DETALHES QUE<br>CONTAM HISTÓRIAS.</h2><p>Explore as imagens do universo '+d.ey+'.</p></div><div class="gallery-tools"><span>Arraste para o lado →</span><button class="gallery-arrow" data-dir="-1" aria-label="Anterior" type="button">←</button><button class="gallery-arrow" data-dir="1" aria-label="Próximo" type="button">→</button></div></div><div class="institution-track" tabindex="0" aria-label="Galeria de trabalhos">'+d.gallery.map((src,i)=>'<figure><img src="'+src+'" loading="lazy" alt="Detalhe de '+d.ey+', imagem '+(i+1)+'"><figcaption>MAÍRA / '+String(i+1).padStart(2,'0')+'</figcaption></figure>').join('')+'</div></section>'}
function questions(){return '<section class="faq-section"><div class="shell faq-layout"><h2 class="display">DÚVIDAS ANTES<br>DO RITUAL?</h2><div class="faq-items"><details><summary>Como escolher o serviço?<span>+</span></summary><p>Explore as opções e conte qual resultado procura. A escolha pode ser alinhada diretamente com a profissional.</p></details><details><summary>Posso levar referências?<span>+</span></summary><p>Sim. Compartilhar ideias de cor, formato e acabamento facilita a conversa sobre suas preferências.</p></details><details><summary>Como consultar disponibilidade?<span>+</span></summary><p>Prepare uma mensagem na página Agendar. A confirmação de horários depende da profissional.</p></details></div></div></section>'}
function finish(title='O PRÓXIMO DETALHE COMEÇA AQUI.'){return '<section class="institution-cta"><div class="institution-cta-media"><img src="'+A.hero+'" loading="lazy" alt=""></div><div class="shell institution-cta-inner"><h2 class="display">'+title+'</h2><p>Conheça as experiências e conte como imagina seu próximo atendimento.</p><a class="btn primary" href="/agendar">Planejar meu atendimento ↗</a></div></section>'}
function bookingPage(){return '<div class="route-page booking-page"><section class="route-hero"><div class="route-hero-bg"><img src="'+A.space+'" alt="Ambiente do atelier"></div><div class="shell"><div class="route-crumb"><a href="/">Início</a> / Agendar</div><h1 class="display">SEU MOMENTO<br>COMEÇA AQUI.</h1><p>Escolha os serviços e prepare sua mensagem para consultar a disponibilidade.</p></div></section><section class="booking-section"><div class="shell booking-layout"><div><h2 class="display">PLANEJE<br>SEU RITUAL.</h2><p>Esta é a prévia do agendamento. Nenhum horário será reservado automaticamente. O contato oficial será configurado antes da publicação.</p><figure class="booking-portrait"><img src="'+A.artist+'" loading="lazy" alt="Retrato editorial da profissional"></figure></div><form id="bookingForm" class="booking-form"><span class="form-step">01 — Escolha seus serviços</span><fieldset class="booking-options"><legend>O que você deseja fazer?</legend><label><input name="service" type="checkbox" value="Mãos & Gel"><span>Mãos & Gel</span></label><label><input name="service" type="checkbox" value="Pés"><span>Pés</span></label><label><input name="service" type="checkbox" value="Sobrancelhas"><span>Sobrancelhas</span></label></fieldset><span class="form-step">02 — Conte um pouco sobre você</span><label class="form-field">Seu primeiro nome<input name="name" autocomplete="given-name" maxlength="70" placeholder="Como podemos chamar você?" required></label><label class="form-field">Período de preferência<select name="period"><option value="">Selecione se desejar</option><option>Manhã</option><option>Tarde</option><option>Noite</option><option>A combinar</option></select></label><label class="form-field">Detalhes e referências<textarea name="note" rows="4" maxlength="600" placeholder="Cor, formato, ocasião, dúvidas..."></textarea></label><p class="form-status" id="bookingStatus" aria-live="polite"></p><button type="submit" class="btn primary">Preparar mensagem ↗</button><div class="message-preview" id="messagePreview" hidden><h3>Sua mensagem está pronta</h3><p id="messageText"></p><div class="message-actions"><button type="button" class="btn" id="copyMessage">Copiar mensagem</button><a class="btn primary" id="shareMessage" target="_blank" rel="noopener" href="https://wa.me/">Compartilhar no WhatsApp ↗</a></div><small>O compartilhamento não envia diretamente ao atelier: o número oficial ainda não foi configurado.</small></div></form></div></section>'+questions()+footer()+'</div>'}
function portfolioPage(){const groups=[['Mãos & Gel',[A.h1,A.h2,A.h3,A.h4]],['Pés',[A.feet,A.f2,A.f3]],['Sobrancelhas',[A.b1,A.b2,A.b3,A.b4]]];return '<div class="route-page portfolio-page"><section class="route-hero"><div class="route-hero-bg"><img src="'+A.h1+'" alt="Manicure em detalhe"></div><div class="shell"><div class="route-crumb"><a href="/">Início</a> / Portfólio</div><h1 class="display">BELEZA EM CADA<br>DETALHE.</h1><p>Uma seleção visual de formas, cores, acabamentos e referências.</p></div></section><section class="portfolio-browser"><div class="shell"><div class="portfolio-browser-head"><h2 class="display">EXPLORE OS<br>TRABALHOS.</h2><div class="filter-tabs" role="group" aria-label="Filtrar portfólio"><button data-filter="Todos" class="active" aria-pressed="true">Todos</button>'+groups.map(g=>'<button data-filter="'+g[0]+'" aria-pressed="false">'+g[0]+'</button>').join('')+'</div></div><div class="portfolio-grid">'+groups.flatMap(g=>g[1].map((src,i)=>'<figure data-category="'+g[0]+'"><img src="'+src+'" loading="lazy" alt="'+g[0]+': imagem '+(i+1)+'"><figcaption>'+g[0]+' <span>↗</span></figcaption></figure>')).join('')+'</div></div></section>'+finish()+footer()+'</div>'}
function aboutPage(d){return '<div class="route-page about-page"><section class="route-hero"><div class="route-hero-bg"><img src="'+A.artist+'" alt="Retrato editorial da profissional"></div><div class="shell"><div class="route-crumb"><a href="/">Início</a> / Sobre</div><h1 class="display">TÉCNICA, INTENÇÃO<br>E ARTE.</h1><p>Uma experiência que começa na escuta e ganha forma nos detalhes.</p></div></section><section class="about-editorial"><div class="shell about-grid"><div><h2 class="display">BELEZA QUE<br>RESPEITA A<br>SUA ESSÊNCIA.</h2><p>A proposta do atelier é valorizar preferências, proporções e identidade pessoal. Cada escolha — cor, forma ou traço — faz parte de um cuidado individual.</p><p>Mãos, pés e sobrancelhas são universos diferentes conectados pela mesma atenção: o detalhe que faz sentido para você.</p><a class="text-link" href="/experiencias">Conhecer as experiências ↗</a></div><figure><img src="'+A.space+'" loading="lazy" alt="Ambiente do atelier"><figcaption>Ambiente, gesto e acabamento.</figcaption></figure></div></section><section class="method"><div class="shell method-layout"><div><h2 class="display">UM JEITO<br>DE CUIDAR.</h2><p>O cuidado é uma sequência de escolhas, não apenas o resultado final.</p></div><div class="method-steps">'+[['Escuta','Entender preferências e referências.'],['Personalização','Definir o serviço e o resultado desejado.'],['Precisão','Atenção ao processo e ao acabamento.'],['Continuidade','Orientações para cuidar do resultado.']].map((x,i)=>'<article><span>0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div></article>').join('')+'</div></div></section>'+detailGallery(d)+finish()+footer()+'</div>'}
function experiencePage(){return '<div class="route-page experience-page"><section class="route-hero"><div class="route-hero-bg"><img src="'+A.hero+'" alt="Composição editorial de beleza"></div><div class="shell"><div class="route-crumb"><a href="/">Início</a> / Experiências</div><h1 class="display">TRÊS UNIVERSOS.<br>UMA ASSINATURA.</h1><p>Descubra a linguagem e a intenção por trás de cada cuidado.</p></div></section><section class="experience-collection"><div class="shell">'+[['LACA','Mãos & Gel','Forma, cor e acabamento.',A.hands,'/maos-e-gel'],['PÉROLA','Pés','Cuidado, ritmo e leveza.',A.feet,'/pes'],['PRECISÃO','Sobrancelhas','Desenho, proporção e expressão.',A.brows,'/sobrancelhas']].map((x,i)=>'<article class="experience-row"><figure><img src="'+x[3]+'" loading="lazy" alt="'+x[1]+'"></figure><div><span>0'+(i+1)+' / '+x[0]+'</span><h2 class="display">'+x[1].toUpperCase()+'</h2><p>'+x[2]+'</p><a class="text-link" href="'+x[4]+'">Conhecer a experiência ↗</a></div></article>').join('')+'</div></section>'+finish()+footer()+'</div>'}
function routePage(d,p){if(p==='/agendar')return bookingPage();if(p==='/portfolio')return portfolioPage();if(p==='/sobre')return aboutPage(d);if(p==='/experiencias')return experiencePage();return '<div class="route-page service-page"><section class="route-hero"><div class="route-hero-bg"><img src="'+d.img+'" alt="'+d.ey+'"></div><div class="shell"><div class="route-crumb"><a href="/">Início</a> / '+d.ey+'</div><h1 class="display">'+d.title+'</h1><p>'+d.support+'</p><a class="btn primary" href="/agendar?servico='+encodeURIComponent(d.ey)+'">Planejar meu atendimento ↗</a></div></section><section class="route-introduction"><div class="shell route-intro-grid"><div><h2 class="display">'+d.head+'</h2><p>'+d.text+'</p></div><figure><img src="'+d.gallery[0]+'" loading="lazy" alt="Detalhe de '+d.ey+'"></figure></div></section><section class="institution-services"><div class="shell"><div class="section-heading"><h2 class="display">ESCOLHA SEU<br>PRÓXIMO CUIDADO.</h2><p>Explore as possibilidades e escolha o que combina com você.</p></div><div class="services-grid">'+d.services.map((x,i)=>'<article class="feature-service"><span>0'+(i+1)+'</span><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div><a href="/agendar?servico='+encodeURIComponent(x[0])+'" aria-label="Planejar '+x[0]+'">↗</a></article>').join('')+'</div></div></section>'+detailGallery(d)+questions()+finish()+footer()+'</div>'}


function render(){
 const p=location.pathname.replace(/\/$/,'')||'/';
 document.title=(p==='/'?'Maíra Beauty Atelier':(routes[p]?.ey||'Maíra')+' — Maíra Beauty Atelier');
 app.innerHTML=p==='/'?home():routePage(routes[p]||routes['/experiencias'],p);
 window.scrollTo(0,0);initRitual();initNav();initGallery();initPortfolio();initBooking();initMotion();
}
function initNav(){
 const btn=document.querySelector('.menu-toggle'),menu=document.querySelector('#mobileNav');
 if(!btn||!menu)return;
 const close=()=>{menu.hidden=true;btn.setAttribute('aria-expanded','false');btn.setAttribute('aria-label','Abrir menu');document.body.classList.remove('menu-open')};
 btn.onclick=()=>{const open=menu.hidden;menu.hidden=!open;btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');document.body.classList.toggle('menu-open',open)};
 menu.querySelectorAll('a').forEach(a=>a.onclick=close);
 document.onkeydown=e=>{if(e.key==='Escape')close()};
 document.querySelectorAll('.nav-links a, .mobile-nav a').forEach(a=>{const on=a.getAttribute('href')===(location.pathname.replace(/\/$/,'')||'/');a.classList.toggle('is-current',on);if(on)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
}
function initGallery(){document.querySelectorAll('.institution-gallery').forEach(g=>{const t=g.querySelector('.institution-track');g.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>t.scrollBy({left:Number(b.dataset.dir)*Math.min(t.clientWidth*.78,620),behavior:'smooth'}))})}
function initPortfolio(){document.querySelectorAll('.filter-tabs button').forEach(b=>b.onclick=()=>{const v=b.dataset.filter;document.querySelectorAll('.filter-tabs button').forEach(x=>{const on=x===b;x.classList.toggle('active',on);x.setAttribute('aria-pressed',String(on))});document.querySelectorAll('.portfolio-grid figure').forEach(f=>f.hidden=v!=='Todos'&&f.dataset.category!==v)})}
function initBooking(){
 const form=document.querySelector('#bookingForm');if(!form)return;
 const preset=new URLSearchParams(location.search).get('servico')||'';
 form.querySelectorAll('input[name="service"]').forEach(x=>{if(preset.includes(x.value)||x.value.includes(preset))x.checked=true});
 form.onsubmit=e=>{e.preventDefault();const sel=[...form.querySelectorAll('input[name="service"]:checked')].map(x=>x.value),name=form.elements.name.value.trim(),status=form.querySelector('#bookingStatus');if(!sel.length){status.textContent='Escolha pelo menos um serviço.';return}if(!name){status.textContent='Informe seu primeiro nome.';form.elements.name.focus();return}
 const period=form.elements.period.value,note=form.elements.note.value.trim(),msg='Olá! Meu nome é '+name+'. Gostaria de consultar a disponibilidade para: '+sel.join(', ')+'.'+(period?' Prefiro '+period+'.':'')+(note?' Observações: '+note+'.':'');
 status.textContent='Mensagem preparada. Nenhum horário foi reservado.';form.querySelector('#messageText').textContent=msg;const preview=form.querySelector('#messagePreview');preview.hidden=false;form.querySelector('#shareMessage').href=WA+'?text='+encodeURIComponent(msg);preview.scrollIntoView({behavior:'smooth',block:'nearest'});
 form.querySelector('#copyMessage').onclick=async()=>{try{await navigator.clipboard.writeText(msg);status.textContent='Mensagem copiada.'}catch{status.textContent='Selecione o texto acima para copiar.'}};
 };
}


function initRitual(){const choices=[...document.querySelectorAll('.choice')],text=document.querySelector('#ritualText'),link=document.querySelector('#ritualWa');if(!choices.length)return;const selected=new Set;choices.forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.choice;selected.has(v)?selected.delete(v):selected.add(v);b.classList.toggle('active',selected.has(v));b.setAttribute('aria-pressed',String(selected.has(v)));const arr=[...selected];text.textContent=arr.length?arr.join(' + '):'nenhum universo selecionado ainda.';link.href='/agendar'+(arr.length?'?servico='+encodeURIComponent(arr.join(', ')):'')}))}
