function initMotion(){if(!window.gsap||!window.ScrollTrigger)return;gsap.registerPlugin(ScrollTrigger);ScrollTrigger.getAll().forEach(t=>t.kill());const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduce&&window.Lenis){const lenis=new Lenis({duration:1.15,smoothWheel:true,wheelMultiplier:.9});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0)}
 gsap.to('.preloader .bar i',{x:'0%',duration:.9,ease:'power3.out'});gsap.to('.preloader',{autoAlpha:0,duration:.8,delay:.75,ease:'power2.inOut',onComplete:()=>document.querySelector('.preloader')?.remove()});
 gsap.to('.hero-line>span',{y:0,filter:'blur(0px)',duration:1.35,stagger:.11,delay:.55,ease:'power4.out'});gsap.to('.hero-sub,.hero-actions',{opacity:1,y:0,duration:1,stagger:.12,delay:1.0,ease:'power3.out'});
 gsap.to('.progress',{scaleX:1,ease:'none',scrollTrigger:{trigger:document.body,start:'top top',end:'bottom bottom',scrub:.3}});gsap.to('#threadPath',{strokeDashoffset:0,ease:'none',scrollTrigger:{trigger:document.body,start:'top top',end:'bottom bottom',scrub:.35}});
 if(document.querySelector('.hero')){gsap.to('.hero-media',{y:80,scale:1.13,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.hero-video',{filter:'saturate(.72) contrast(1.18) brightness(.56)',ease:'none',scrollTrigger:{trigger:'.hero',start:'25% top',end:'bottom top',scrub:true}});gsap.to('.cinema-cut',{clipPath:'circle(150% at 78% 82%)',ease:'none',scrollTrigger:{trigger:'.hero',start:'72% top',end:'bottom top',scrub:true}});gsap.to('.lacquer-orb',{y:-120,x:-70,rotate:18,scale:1.23,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.hero-copy-inner',{y:-70,opacity:.3,ease:'none',scrollTrigger:{trigger:'.hero',start:'35% top',end:'bottom top',scrub:true}});
 gsap.from('.portrait-a',{y:110,rotate:-3,scale:.95,scrollTrigger:{trigger:'.manifest',start:'top 75%',end:'center center',scrub:1}});gsap.from('.portrait-b',{y:-80,x:50,rotate:4,scrollTrigger:{trigger:'.manifest',start:'top 70%',end:'bottom 75%',scrub:1}});
 const u=gsap.timeline({scrollTrigger:{trigger:'.universes',start:'top top',end:'bottom bottom',scrub:1}});u.to('.u1',{scale:.86,yPercent:-30,opacity:0,duration:1},0).to('.u2',{scale:1,yPercent:0,opacity:1,duration:1},0).to('.u2',{scale:.86,yPercent:-30,opacity:0,duration:1},1).to('.u3',{scale:1,yPercent:0,opacity:1,duration:1},1);
 const cinema=document.querySelector('.cinema-interlude');if(cinema){const ct=gsap.timeline({scrollTrigger:{trigger:cinema,start:'top top',end:'bottom bottom',scrub:1}});ct.fromTo('.cinema-video',{scale:1.02,yPercent:0},{scale:1.16,yPercent:-4,duration:2,ease:'none'},0).fromTo('.beat-1',{opacity:1,y:80,filter:'blur(8px)'},{opacity:1,y:0,filter:'blur(0px)',duration:.6},0).to('.beat-1',{opacity:0,y:-90,filter:'blur(10px)',duration:.55},.75).fromTo('.beat-2',{opacity:0,y:100,filter:'blur(10px)'},{opacity:1,y:0,filter:'blur(0px)',duration:.65},.9).to('.cinema-note',{opacity:.2,y:-30,duration:.5},1.45);}document.querySelectorAll('.chapter').forEach((s,i)=>{const main=s.querySelector('.frame.main'),small=s.querySelector('.frame.small'),tiny=s.querySelector('.frame.tiny');if(main)gsap.fromTo(main,{scale:.82,y:80},{scale:1.02,y:-20,ease:'none',scrollTrigger:{trigger:s,start:'top bottom',end:'bottom top',scrub:1}});if(small)gsap.fromTo(small,{y:140,rotate:5},{y:-40,rotate:-2,ease:'none',scrollTrigger:{trigger:s,start:'top bottom',end:'bottom top',scrub:1.2}});if(tiny)gsap.fromTo(tiny,{y:-70,rotate:-5},{y:60,rotate:3,ease:'none',scrollTrigger:{trigger:s,start:'top bottom',end:'bottom top',scrub:1.1}})});
 document.querySelectorAll('.precision-svg path').forEach((p,i)=>gsap.to(p,{strokeDashoffset:0,ease:'none',scrollTrigger:{trigger:'.brow-media',start:'top 70%',end:'bottom 40%',scrub:1},delay:i*.1}));
 const track=document.querySelector('.track');if(track){const getX=()=>Math.max(0,track.scrollWidth-innerWidth+80);gsap.to(track,{x:()=>-getX(),ease:'none',scrollTrigger:{trigger:'.portfolio',start:'top top',end:'bottom bottom',scrub:1,invalidateOnRefresh:true}})}
 gsap.to('.final-bg',{scale:1,y:-20,ease:'none',scrollTrigger:{trigger:'.final',start:'top bottom',end:'bottom top',scrub:1}})}
 document.querySelectorAll('.route-hero-bg img').forEach(img=>gsap.to(img,{scale:1.12,y:55,ease:'none',scrollTrigger:{trigger:'.route-hero',start:'top top',end:'bottom top',scrub:true}}));
 document.querySelectorAll('.service').forEach((el,i)=>gsap.from(el,{y:45,opacity:0,duration:.7,delay:i*.04,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%'}}));
 ScrollTrigger.create({start:40,onUpdate:self=>document.querySelector('.nav')?.classList.toggle('scrolled',self.scroll()>40)});const scenes=[...document.querySelectorAll('[data-scene]')],dots=[...document.querySelectorAll('.hud i')];scenes.forEach(s=>ScrollTrigger.create({trigger:s,start:'top center',end:'bottom center',onToggle:x=>{if(x.isActive){const n=+s.dataset.scene;dots.forEach((d,i)=>d.classList.toggle('active',i===n))}}}));ScrollTrigger.refresh();}
 document.addEventListener('click',e=>{const a=e.target.closest('a[href^="/"]');if(!a||a.target)return;const href=a.getAttribute('href');if(!routes[href]&&href!=='/')return;e.preventDefault();history.pushState({},'',href);render()});window.addEventListener('popstate',render);render();
